twig:
    file_name_pattern: '*.twig'
    form_themes: ['admin/form_theme.html.twig']
    globals:
        templateService: '@App\Service\TemplateService'
        tinymce_key: '%env(string:TINYMCE_API_KEY)%'

when@test:
    twig:
        strict_variables: true
